selected_scheme scheme-small
TEXDIR C:\texlive\2026
TEXMFLOCAL C:\texlive\texmf-local
TEXMFSYSVAR C:\texlive\2026\texmf-var
TEXMFSYSCONFIG C:\texlive\2026\texmf-config
TEXMFVAR C:\texlive\texmf-var
TEXMFCONFIG C:\texlive\texmf-config
TEXMFHOME ~\texmf
instopt_adjustpath 1
instopt_letter 0
tlpdbopt_install_docfiles 0
tlpdbopt_install_srcfiles 0
tlpdbopt_desktop_integration 0
tlpdbopt_file_assocs 0
tlpdbopt_w32_multi_user 0
collection-basic 1
collection-latex 1
collection-latexrecommended 1
collection-latexextra 1
collection-langjapanese 1
